version: '3.8'

services:
  node_app:
    image: node:18
    container_name: my_node_app_bai8
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydb
    command: "npm start"
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0
    container_name: my_mysqlbai8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydb
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
