version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: my_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

  mongoexpress:
    image: mongo-express:latest
    container_name: my_mongoexpress
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    restart: always

volumes:
  mongodb_data:
