version: '3.8'

services:
  flask_app:
    image: python:3.9
    container_name: my_flask_app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
    command: "flask run"
    restart: always
