version: '3.8'

services:
  node_app:
    image: node:18
    container_name: my_node_app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: "npm start"
    environment:
      - NODE_ENV=development
    restart: always
